name: Go build
on: [push]
jobs:

  build:
    name: Build
    runs-on: [ubuntu-18.04]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run GolangCI-Lint
      uses: Mushus/golangci-linter@v1

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Test
      run: go test ./...
